Add category level attributes api support
kyto-gmbh/alibaba-sdk-php pull request #3
Opened 2024-02-09 14:54 UTC by Dominik-Czulak

This PR implements support for alibaba's "alibaba.icbu.category.level.attr.get" api request method.

Also the AlibabaException constructor was adjusted to accept nullable subMessage and subCode, as api errors in the newly implemented don't have those.

2024-02-09 15:09 UTC, Dominik-Czulak commented on src/Model/CategoryAttribute.php
>      // TODO: change to enums once all values would be known
What exactly was the idea with enums here? Some kind of validation by checking if it is one of those values?

2024-02-16 09:51 UTC, Dominik-Czulak commented on src/Factory/CategoryFactory.php
> +        $decodedValues = json_decode($data['values'], true);
The response value is a decoded json, that is correct. But "values" returns a json string, which we have to decode again :sweat_smile:

2024-02-16 14:19 UTC, Dominik-Czulak commented on src/Endpoint/CategoryEndpoint.php
> +            'attribute_value_request' => json_encode($attributeValueRequest)
It needs a json encoded string in the request there :sweat_smile:

2024-02-16 14:19 UTC, Dominik-Czulak commented on src/Exception/AlibabaException.php
> +        private ?string $subCode,
It was working before specifically expecting it, but I guess it could lead to warnings and such, so I checked in the throw explicitly as well

2024-02-16 14:21 UTC, Dominik-Czulak commented on src/Factory/CategoryFactory.php
> +    public function createLevelAttribute(array $data): CategoryLevelAttribute
Not anymore :)

2024-02-16 14:21 UTC, Dominik-Czulak commented on src/Factory/CategoryFactory.php
> +    public function createLevelAttributeValue(array $data): CategoryLevelAttributeValue
Not anymore :)

2024-02-16 14:21 UTC, Dominik-Czulak commented on src/Model/CategoryAttribute.php
>      // TODO: change to enums once all values would be known
Done.

2024-02-16 14:47 UTC, Dominik-Czulak commented on src/Exception/AlibabaException.php
>          $message = sprintf('%s. Sub-code: "%s". Sub-message: "%s".', $message, $this->subCode, $this->subMessage);
Changed it, so that subMessage and subCode part are only added, if they are not null

2024-02-20 11:12 UTC, vstelmakh requested changes

2024-02-20 11:12 UTC, vstelmakh commented on tests/Factory/CategoryFactoryTest.php
> +        yield ['no values' => $data, $expected];
This array looks weird. As first element has `string` key while the second is `int`. It seems like you tried to name the dataset (but failed a bit :sweat_smile:). I think it should be like:
```php
yield 'no values' => [$data, $expected];
```

Same for all yields below.

2024-02-20 12:31 UTC, Dominik-Czulak commented on src/Exception/AlibabaException.php
> +        private ?string $subCode,
You might be right. During development I think I had cases, where I had errors without sub messages and codes. I double checked right now, and could not reproduce it. Instead now there is an error thrown if the "result_list" is empty, as this means, that the combination of category, attribute and value id is invalid.

I reverted the AlibabaException changes.

2024-02-22 10:15 UTC, Dominik-Czulak commented on src/Endpoint/CategoryEndpoint.php
> +            ?? throw new \RuntimeException($errorMessage);
Done. If you have better ideas for naming the exceptions. Please let me know :)

2024-02-26 11:58 UTC, vstelmakh requested changes

2024-02-26 11:58 UTC, vstelmakh commented on src/Exception/AlibabaException.php
> +abstract class AlibabaException extends \RuntimeException
I'm not sure where to start a discussion. I guess on abstract would be fine. :slightly_smiling_face: 

I like the way of having abstract Alibaba exception. But I'm not sure about the name. It's quite popular code style to add `Abstract` prefix to abstract classes. While it's not part of [PER Coding Style 2.0](https://www.php-fig.org/per/coding-style/). So I'm not sure which is better here `AbstractAlibabaException` or `AlibabaException`. 

`AlibabaException` - looks better here IMO.

While I would definitely suggest to rename other exceptions:
- `AlibabaApiError` to `ResponseException`
- `UnexpectedApiResultException` to `UnexpectedResultException`

to be shorter and nicer.

As both of this specific exceptions extending `AlibabaException`, there is no need to include this into name. Same for the `API`, the whole package is about API, so it could be avoided in exception name. The last but not least, I would always suffix exception with `Exception` (not `Error`) this will make it clear that this is actually exception.

2024-02-26 12:51 UTC, Dominik-Czulak commented on src/Exception/AlibabaException.php
> +abstract class AlibabaException extends \RuntimeException
Yeah I like the naming. Done.

2024-02-26 17:27 UTC, vstelmakh approved these changes

2024-03-15 09:32 UTC, Sven-Erdmann approved these changes

2024-03-22 10:46 UTC, merged